sudo: required

services:
  - docker

before_install: 
  - docker build -t rlum/core core
  - docker build -t rlum/stable stable
    # - docker build -t rlum/dev dev

script:
  - docker run -d --name rlumcore rlum/core
  - docker run -d --name rlumstable rlum/stable
    # - docker run -d --name rlumdev rlum/dev
  - sleep 5 && docker ps | grep rlum
  - docker rm -f $(docker ps -a -q)